package com.lambui.healthcare_doctor.constant

object ExtraKeyConstants {
    const val EXTRA_DETAIL_MESSAGE = "EXTRA_DETAIL_MESSAGE"
    const val PATH_FILE_REGEX = "(\\d+)$"
    const val EXTRA_DOCTOR = "EXTRA_DOCTOR"
    const val REQUEST_CODE_PUSH_DOCTOR_DETAIL = 3001
    const val KEY_ID_SPECIALIST = "KEY_ID_SPECIALIST"
    const val KEY_NEAR_BY = "KEY_NEAR_BY"
    const val KEY_PENDING_ITEM = "KEY_PENDING_ITEM"
    const val KEY_CONFIRM_ITEM = "KEY_CONFIRM_ITEM"
    const val KEY_COMPLETE_ITEM = "KEY_COMPLETE_ITEM"
    const val KEY_CANCEL_ITEM = "KEY_CANCEL_ITEM"
    const val EXTRA_HAS_NOTIFICATION = "EXTRA_HAS_NOTIFICATION"
    const val EXTRA_ITEM_APPOINTMENT = "EXTRA_ITEM_APPOINTMENT"
    const val EXTRA_ITEM_APPOINTMENT_HISTORY = "EXTRA_ITEM_APPOINTMENT_HISTORY"
    const val EXTRA_ITEM_APPOINTMENT_CANCEL = "EXTRA_ITEM_APPOINTMENT_CANCEL"
    const val KEY_STATUS = "STATUS"
}